### ISSUE TITLE
tutorial is in need

### ISSUE THREAD

**Issue by Ellomend** [neuronetio/elastigantt#1]
please provide tutorial for clear vue cli 2 webpack or vue cli 3
Seems awesome but was unable to add it to my project.

Thank you anyway

**Comment by neuronetio** [comment]
ok, soon I'll do some tutorials (maybe at the weekend)
I'll let you know
thanks

**Comment by neuronetio** [comment]
elastigantt was updated to work with webpack as component too, take a look at README.MD
more documentation soon

**Comment by neuronetio** [comment]
I've made webpack demo project here https://github.com/neuronetio/gantt-elastic-webpack
