### ISSUE TITLE
Error while using

### ISSUE THREAD

**Issue by wang-cola** [neuronetio/elastigantt#3]
6/5000  
Follow your tutorial，will be prompted: "Vue is not defined"
![image](https://user-images.githubusercontent.com/21015798/48248424-35635480-e432-11e8-8be8-f821ea07c0af.png)
![image](https://user-images.githubusercontent.com/21015798/48248440-457b3400-e432-11e8-8527-c9cc22add250.png)
I don't know what's wrong. I need your help

**Comment by wangraoji** [comment]
I also encountered the same problem, I need help too

**Comment by neuronetio** [comment]
`<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>`


pt., 9 lis 2018, 08:38: 邪七 <notifications@github.com> napisał(a):

**Comment by wang-cola** [comment]
I use vue-cli，not reference vue.js in index.html
my vue is in my package.json
![image](https://user-images.githubusercontent.com/21015798/48250136-3c8d6100-e438-11e8-8b64-ff867868e020.png)

**Comment by neuronetio** [comment]
I will update this lib on this weekend, maybe today so it will work with
webpack as pure component.

>

**Comment by wang-cola** [comment]
thank you very much

**Comment by neuronetio** [comment]
@wang-cola elastigantt as webpack module component should work now

**Comment by neuronetio** [comment]
I've made webpack demo project here https://github.com/neuronetio/gantt-elastic-webpack
